os:
  - linux

language: java
jdk:
- openjdk8
dist: trusty
branches:
  only:
  - master
  - dev
  - backend

services:
  - docker

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"

before_script: cd backend

script:
  # BUILD
  - "./gradlew clean build"
  
  # DOCKER
  - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
  - docker build -t colletter:latest --build-arg JAR_FILE=build/libs/*.jar .
  - docker tag colletter:latest ${DOCKER_USERNAME}/colletter:latest
  - docker push ${DOCKER_USERNAME}/colletter:latest
