os:
  - linux

language: java
jdk:
- openjdk8

branches:
  only:
  - master
  - dev
  - backend

services:
  - docker

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"

before_script: cd backend

script:
  # BUILD
  - "./gradlew clean build"
