language: java
jdk:
  - openjdk8

branches:
  only:
    - master
    - dev
    - backend

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script:
 - ./gradlew clean build

before_script: cd backend