INSERT INTO category (name_en, name_kr, image) VALUES ('DESIGN', '디자인', null)
INSERT INTO category (name_en, name_kr, image) VALUES ('EDUCATION', '교육', null)
INSERT INTO category (name_en, name_kr, image) VALUES ('DEVELOPMENT', '개발', null)
INSERT INTO category (name_en, name_kr, image) VALUES ('ART_CULTURE', '문화예술', null)
INSERT INTO category (name_en, name_kr, image) VALUES ('COMMON_SENSE', '상식', null)
INSERT INTO category (name_en, name_kr, image) VALUES ('ENTERPRISE', '기업', null)
INSERT INTO category (name_en, name_kr, image) VALUES ('FINANCE', '금융', null)
INSERT INTO category (name_en, name_kr, image) VALUES ('IT_STARTUP', 'IT-스타트업', null)
INSERT INTO category (name_en, name_kr, image) VALUES ('POLITICS', '정치', null)
INSERT INTO category (name_en, name_kr, image) VALUES ('RELIGION', '종교', null)
INSERT INTO category (name_en, name_kr, image) VALUES ('TREND', '트렌드', null)

INSERT INTO user (role, email, name, image, theme, access_token, refresh_token, bookmarks_count) VALUES (0, 'colletter', '뒤끝', '0', 0, '', '', 0)
