INSERT INTO category (category_id, name, image) VALUES ('c_0', '디자인', null )
INSERT INTO category (category_id, name, image) VALUES ('c_1', '게임', null )
INSERT INTO category (category_id, name, image) VALUES ('c_2', '음식', null )
INSERT INTO category (category_id, name, image) VALUES ('c_3', '교육', null )
INSERT INTO category (category_id, name, image) VALUES ('c_4', '개발', null )
INSERT INTO category (category_id, name, image) VALUES ('c_5', '기획', null )
